name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and start SUT with test profile
        run: java -jar ./artifacts/app-ibank.jar -P:profile=test &

      - name: Wait for SUT to be ready
        run: |
          for i in {1..20}; do
            if curl --silent --fail http://localhost:9999; then
              echo "SUT is up!"
              break
            fi
            echo "Waiting for application to start... Attempt $i"
            sleep 2
          done

      - name: Run tests
        run: ./gradlew test --stacktrace --info -Dselenide.headless=true